### ISSUE TITLE
New version does not look like github's markdown preview for code blocks

### ISSUE THREAD

**Issue by ventz** [aero31aero/markdown-editor#20]
Hi,

For some reason the new version does not look like github's preview (at least under Chrome).
(Specifically around code blocks)

The older version was a perfect clone of github's markdown "preview".

**Comment by aero31aero** [comment]
Hey! Can you please show some screenshots of the issue? That'd be really helpful in debugging this.

**Comment by aero31aero** [comment]
Closing issue on this repo.

**Comment by ventz** [comment]
![screen shot 2018-02-12 at 5 12 24 pm](https://user-images.githubusercontent.com/901168/36122613-062d8864-1018-11e8-99d2-905b79e64be7.png)

**Comment by ventz** [comment]
@aero31aero - Uploaded. By the way - do you maintain it on this repository, or the jbt one?

**Comment by aero31aero** [comment]
Its maintained on the main repo (jbt) now. I should close the issues feature on this repo. I was using this for tracking what I wanted with my fork.

I don't recall making any changes to the rendering part of the code, so I have to assume that the issue you're mentioning is probably deeper (in the markdown parser, perhaps?). What is the expected output/how does it look like on GitHub?

**Comment by ventz** [comment]
Let me reply just there then, so it's all in one place.

Linking it from here: https://github.com/jbt/markdown-editor/issues/83
